services:
  rocker:
    build: .
    container_name: rocker-starter
    environment:
      - DISABLE_AUTH=true
    platform: linux/amd64
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio
