---
title: "HD Quarto template R"
author: "Holger Doering"
date: today
execute:
  cache: true
  messages: true
  warning: false
format:
  html:
    code-fold: true
    df-print: kable
    embed-resources: true
    toc: true

---

```{r corepacks}
library(conflicted) # create errors for function name conflicts

library(tidyverse)
conflicts_prefer(dplyr::filter, .quiet = TRUE)
library(knitr) # layout // tables in RMarkdown with kable()

ggplot2::theme_set(theme_minimal())
options(scipen = 999) # suppress scientific notation

library(broom) # models // tidy results
library(ggeffects) # models // visualize model effects
library(patchwork) # plots  // arrange
library(reactable) # layout // interactive data tables
library(skimr) # packages // used (once) but not loaded

# conflict_scout()

round_numeric_variables <- function(data, digits = 0) {
  mutate(data, across(
    where(is.numeric),
    \(.x) format(round(.x, digits), scientific = FALSE)
  ))
}
```

---

<https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/cars.html>


## Summary data

```{r data}
cars <-
  datasets::mtcars |>
  rownames_to_column(var = "car") |>
  mutate(across(c(cyl, gear), as_factor)) |>
  as_tibble()
```


```{r check}
#| eval=FALSE

glimpse(cars)
summary(cars)
```


```{r skim-data}
cars |> skim()
```

```{r skim-numeric}
cars_skim <-
  cars |>
  skim() |>
  select(skim_variable, matches("^numeric")) |>
  rename_with(~ str_remove(.x, "^skim_|^numeric\\.")) |>
  round_numeric_variables(1)
```


## Visualization

```{r figure, message=FALSE}
pl1 <- ggplot(cars, aes(
  x = hp,
  y = mpg,
  color = cyl,
  shape = cyl
)) +
  geom_point(size = 3)

pl2 <- ggplot(cars, aes(x = hp, y = mpg)) +
  geom_point(alpha = 0.5) +
  geom_smooth(se = FALSE)

pl1 + pl2
```


## Linear model

```{r model}
m1 <- lm(mpg ~ log(hp) + gear, data = cars)

tidy(m1) |> kable(digits = 2)
glance(m1) |> kable(digits = 2)

ggpredict(m1, terms = c("hp", "gear")) |> plot()
```


## Explore data

```{r explore}
cars |>
  select(car, mpg, hp, cyl, gear) |>
  reactable(searchable = TRUE, striped = TRUE)
```


## References

```{r reference, eval=FALSE}
library(httr2)

get_doi_reference <- function(doi) {
  request(paste0("https://doi.org/", doi)) |>
    req_headers("Accept" = "text/x-bibliography") |>
    req_perform() |>
    resp_body_string()
}

references_doi <- c(
  "10.21105/joss.01686"
)

references <- map_chr(references_doi, get_doi_reference)
```
